# HW Questions (Numpy):
Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [2]:
import numpy as np
A = np.array([[1,2],[2,3],[6,7],[6,9],[4,2]]).T
B = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [3]:
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print(vertical_stack)
print(horizontal_stack)

[[1 2 6 6 4]
 [2 3 7 9 2]
 [1 2 3 4 5]
 [5 4 3 2 1]]
[[1 2 6 6 4 1 2 3 4 5]
 [2 3 7 9 2 5 4 3 2 1]]


Find common elements between A and B. [Hint : Intersection of two sets]

In [4]:
intersect = np.intersect1d(A,B)
print(intersect)

[1 2 3 4]


Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [5]:
mask = np.where((A >= 5) & (A <= 10), True, False)
masked = mask * A
print(masked)

[[0 0 6 6 0]
 [0 0 7 9 0]]


Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filter = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filter)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# HW Questions (Pandas):
From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [7]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
x = df.columns.tolist()
lookinFor = ['Manufacturer', 'Model', 'Type']
values = [x.index(name) for name in lookinFor if name in x]
for index in values:
    column_name = x[index]
    print(f'{column_name} has:')
    print(df[column_name][::20].reset_index(drop=True).to_string(index=False)) 
    print() 



Manufacturer has:
   Acura
Chrysler
   Honda
 Mercury
  Subaru

Model has:
Integra
LeBaron
Prelude
 Cougar
 Loyale

Type has:
  Small
Compact
 Sporty
Midsize
  Small



Replace missing values in Min.Price and Max.Price columns with their respective mean.

    df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
x = df.columns.tolist()
lookinFor = ['Min.Price', 'Max.Price']
values = [x.index(name) for name in lookinFor if name in x]
for column in lookinFor:
    if column in df.columns:
        mean_value = df[column].mean()  
        df[column].fillna(mean_value, inplace=True)
for column in lookinFor:
    print(f'{column} has:')
    print(df[column])
    print()


Min.Price has:
0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64

Max.Price has:
0     18.800000
1     38.700000
2     32.300000
3     44.600000
4     21.459091
        ...    
88    22.700000
89    22.400000
90    23.700000
91    23.500000
92    28.500000
Name: Max.Price, Length: 93, dtype: float64



/var/folders/gw/75zv3r9x3rn8lcckqvxz7p2m0000gn/T/ipykernel_3953/2436971126.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mean_value, inplace=True)


How to get the rows of a dataframe with row sum > 100?

    df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [16]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
newdf = []

for row in range(len(df.values)):
    x = sum(df.values[row])
    if x > 100:
        newdf.append(df.values[row])
newdf = pd.DataFrame(newdf)
final_array = newdf.to_numpy()
print(df.values)
print(final_array)

[[28 33 24 36]
 [24 33 10 37]
 [18 21 32 29]
 [19 39 11 18]
 [20 12 25 18]
 [14 34 20 39]
 [21 27 34 23]
 [32 10 29 38]
 [26 10 26 29]
 [31 30 18 25]
 [25 18 39 27]
 [37 23 18 17]
 [29 39 38 35]
 [25 26 31 27]
 [34 28 16 35]]
[[28 33 24 36]
 [24 33 10 37]
 [14 34 20 39]
 [21 27 34 23]
 [32 10 29 38]
 [31 30 18 25]
 [25 18 39 27]
 [29 39 38 35]
 [25 26 31 27]
 [34 28 16 35]]
